### ISSUE TITLE
Seven mod combo crashes Architectury API

### ISSUE THREAD

**Issue by AlexanderwithaA** [TechTastic/kubevs#1]
### Mod Name

Architectury API

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Fabric

### Issue description

When KubeJS, KubeVS, KubeJSoffline, Valkyrian Skies 2, Rhino, Architectury API, and the Fabric API are all installed, the architectury api crashes the game due to this it seems

java.lang.ClassNotFoundException: org.valkyrienskies.core.impl.datastructures.DenseBlockPosSet

### Issue reproduction

Install KubeJS, KubeVS, KubeJSoffline, Valkyrian Skies 2, Rhino, Architectury API, and Fabric API on a fabric instance then run the game.
(Latest version of each as of today 10/28/23)

### Logs

[latest.log](https://github.com/TechTastic/kubevs/files/13197319/latest.log)

**Comment by TechTastic** [comment]
This is due to VS2 restructuring their code in the latest beta version. This will be remedied soon but I am waiting for a proper API before attempting to update

**Comment by AlexanderwithaA** [comment]
I did find a work around, architectury api is what was throwing all the errors, but removing kubejsoffline is what fixed it.

**Comment by TechTastic** [comment]
Fixed in latest
